use std::io::{self, Read};
use std::error::Error;
use chrono::Utc;

fn get_urls() -> Result<Vec<String>, io::Error> {
    let mut buffer = String::new();
    io::stdin().read_to_string(&mut buffer)?;
    Ok(buffer.trim().split("\n").map(String::from).collect())
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let mut feeds = rssx::fetch_all_feeds(get_urls()?).await?;
    let today = Utc::today().format("%Y-%m-%d");

    // TODO: Don't clone
    feeds.sort_by_key(|f| f.title.clone());

    println!("# RSS\n");
    println!("*Autogenerated by [rssx](https://github.com/timothyandrew/rssx) on {}*\n", today);

    for feed in feeds.iter() {
        let md = rssx::serialize_feed(&feed);
        println!("{}", md);
    }

    Ok(())
}
